name: Angular GitHub CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
defaults:
  run:
    working-directory: angular

jobs:
  build:
    name: Build and lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node
        uses: actions/setup-node@v1
        with:
          node-version: "16.14.0"

      - name: Install dependencies
        run: npm ci --force

      - name: Build
        run: npm run build

      - name: Test
        run: npm run lint:all
